server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true

  rabbitmq:
    addresses: amqps://nmirxeeo:xbw5ugx-i3ed3VNFCFmQvHdbaJ0oOblu@jackal.rmq.cloudamqp.com/nmirxeeo

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'


eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost