server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CassioLeodegario/ead-config-server-repo
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_KEY}
        encrypt:
          enabled: false

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost


