server:
  port: 8888
spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CassioLeodegario/ead-config-server-repo
          default-label: main
          username: ${GIT_USERNAME}
          password: ${GIT_KEY}
        encrypt:
          enabled: false

ead:
  configServer:
    username: configServer
    password: ${CONFIG_PASSWORD}
  serviceRegistry:
    username: serviceRegistry
    password: ${REGISTRY_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


